npx google-closure-compiler \
--language_in ECMASCRIPT5_STRICT \
--language_out ECMASCRIPT5_STRICT \
--warning_level VERBOSE \
--output_wrapper "(function() {%output%})();" \
--js=classes/CustomWindow.js \
--js=classes/Dice.js \
--js=classes/ScoreCounter.js \
--js=classes/DiceApplication.js \
--js=classes/TimeManager.js \
--js=classes/ClockApplication.js \
--js=classes/DragAndDropHandler.js \
--js=Main.js \
--js_output_file=out.js