npx google-closure-compiler \
--language_in ECMASCRIPT5_STRICT \
--language_out ECMASCRIPT5_STRICT \
--warning_level VERBOSE \
--js=classes/Window.js \
--js=classes/Dice.js \
--js=classes/Counter.js \
--js=classes/DiceApplication.js \
--js=classes/TimeManager.js \
--js=classes/ClockApplication.js \
--js=classes/factories/WindowFactory.js \
--js=classes/handlers/DragAndDropHandler.js \
--js=classes/App.js \
--js=main.js \
--js_output_file=out.js